src/Entity/Property.php
<?php

namespace App\Entity;

use App\Repository\PropertyRepository;
use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass=PropertyRepository::class)
 */
class Property
{

    const HEAT = [
        0 => 'Electric',
        1 => 'Gaz'
    ];

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="integer")
     */
    private $surface;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $badrooms;

    /**
     * @ORM\Column(type="integer")
     */
    private $floor;

    /**
     * @ORM\Column(type="integer")
     */
    private $heat;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $postal_code;

    /**
     * @ORM\Column(type="boolean",options={"default": false})
     */
    private $sold = false;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private $created_at;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }

    /**
     * @ORM\Column(type="integer")
     */
    private $price;

    public function getFormatedPrice():string
    {
        return number_format($this->price,0,'',' ');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getSlug(): ?string
    {
        return (new Slugify())->slugify($this->title);
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSurface(): ?int
    {
        return $this->surface;
    }

    public function setSurface(int $surface): self
    {
        $this->surface = $surface;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    public function getBadrooms(): ?int
    {
        return $this->badrooms;
    }

    public function setBadrooms(int $badrooms): self
    {
        $this->badrooms = $badrooms;

        return $this;
    }

    public function getFloor(): ?int
    {
        return $this->floor;
    }

    public function setFloor(int $floor): self
    {
        $this->floor = $floor;

        return $this;
    }

    public function getHeat(): ?int
    {
        return $this->heat;
    }

    public function setHeat(int $heat): self
    {
        $this->heat = $heat;

        return $this;
    }

    public function getHeatType():string
    {
        return self::HEAT[$this->heat];
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): self
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getSold(): ?bool
    {
        return $this->sold;
    }

    public function setSold(bool $sold): self
    {
        $this->sold = $sold;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPrice(): ?int
    {
        return $this->price;
    }

    public function setPrice(int $price): self
    {
        $this->price = $price;

        return $this;
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class HomeController extends AbstractController
{
    /**
     * @Route("/home", name="home")
     * @param PropertyRepository $repository
     * @return Response
     */
    public function index(PropertyRepository $repository): Response
    {
        $property = $repository->findLatest();
        return $this->render('home/index.html.twig', [
            'properties' => $property,
        ]);
    }
}

src/Controller/PropertyController.php
<?php

namespace App\Controller;

use App\Entity\Property;
use App\Repository\PropertyRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class PropertyController extends AbstractController
{
    /**
     * @var PropertyRepository
     */
    private $repository;

    public function __construct(PropertyRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * @Route("/property", name="property.index")
     */
    public function index(): Response
    {
        $property = $this->repository->findAllVisible();
        $property[0]->setSold(true);
        return $this->render('property/index.html.twig', [
            'current_menu' => 'properties',
            'controller_name' => 'PropertyController',
        ]);
    }

    /**
     * @Route("/propertys/{slug}-{id}", name="property.show", requirements={"slug": "[a-z0-9\-]*"})
     */
    public function show(Property $property,string $slug): Response
    {
        if ($property->getSlug() !== $slug)
        {
            return $this->redirectToRoute('property.show',[
                'id'=>$property->getId(),
                'slug'=>$property->getSlug()
            ],301);
        }

        return $this->render("home/show.html.twig", [
            'property' => $property,
            'current_menu' => 'properties'
        ]);
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}Welcome!
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    {% block stylesheets %}
        {# {{ encore_entry_link_tags('app') }} #}
    {% endblock %}

    {% block javascripts %}
        {# {{ encore_entry_script_tags('app') }} #}
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ path('home') }}">Mon Agence</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link {% if current_menu is defined and current_menu == 'properties'%}active{% endif %}"  aria-current="page" href="{{ path('property.index') }}">Achter</a>
                </li>
            </ul>
            <form class="d-flex">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"
        integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13"
        crossorigin="anonymous"></script>
{% block body %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>
</body>
</html>

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello HomeController!
{% endblock %}

{% block body %}
    <div class="jumbotron text-center">
        <h1>Hello Devs</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dolores error libero, quis sequi unde voluptate?
            Beatae
            deleniti eaque eligendi in itaque nemo optio quam unde voluptas voluptate? Commodi, magni, mollitia?</p>
    </div>

    <div class="container">
        <h2>Les derniers biens</h2>
        <div class="row flex">
            {% for property in properties %}
                <div class="col-3">
                    <div class="card">
                        <div class="card-body">
                            <a href="{{ path('property.show',{id: property.id, slug: property.slug}) }}">
                                <h5 class="card-title">{{ property.title }}</h5>
                            </a>
                            <p class="card-text">{{ property.city }} ({{ property.postalCode }})</p>
                            <div class="text-primary" style="font-weight: bold">{{ property.formatedPrice}} TND</div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

templates/home/show.html.twig
{% extends 'base.html.twig' %}

{% block title property.title %}


{% block body %}
    <div class="jumbotron">
        <div class="container">
            <div class="row">
                <div class="col-md-8"></div>
                <div class="col-md-4">
                    <h1>{{property.title}}</h1>
                    <h2>{{property.rooms}} piéces - {{property.surface}} </h2>
                    <div class="text-primary" style="font-size: 4rem;font-weight: bold;">{{property.formatedPrice}} TND</div>
                    <a href="#" class="btn btn-primary">Contacter l'agence</a>
                </div>
            </div>
        </div>
    </div>
    <div class="container mt-4">
        <p>{{property.description | nl2br}}</p>
        <div class="row">
            <div class="col-md-8">
                <h2>Caractéristique</h2>
                <table class="table table-striped">

                    <tr>
                        <td>Surface habitable</td>
                        <td>{{property.surface}}</td>
                    </tr>
                    <tr>
                        <td>Piéce</td>
                        <td>{{property.rooms}}</td>
                    </tr>
                    <tr>
                        <td>Chambre</td>
                        <td>{{property.badrooms}}</td>
                    </tr>
                    <tr>
                        <td>Etage</td>
                        <td>{{property.floor}}</td>
                    </tr>
                    <tr>
                        <td>Chauffage</td>
                        <td>{{property.heatType}}</td>
                    </tr>

                </table>
            </div>
            <div class="col-md-4">
                <h2>Spécificités</h2>
            </div>
        </div>

    </div>

{% endblock %}

templates/property/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Tous nos bien{% endblock %}

{% block body %}
    <div class="jumbotron text-center">
        <div class="container">
            <h1>Voir tous nos bien</h1>
        </div>
    </div>
{% endblock %}